import crypto from 'node:crypto';
import {createHubStore} from './hub_store.mjs';

const PROTOCOL_VERSION='1.3.0-r10.26';
const CREDENTIAL_TTL_MS=30*24*60*60*1000;
const ENROLL_TTL_MS=2*60*1000;
const MAX_MESSAGE_TTL_MS=24*60*60*1000;
const MAX_PAYLOAD_BYTES=64*1024;
const ROLES=new Set(['CLIENTE','MASTER','NEXA']);
const MESSAGE_TYPES=new Set(['HEARTBEAT','SUPPORT_REQUEST','SUPPORT_MESSAGE','SUPPORT_STATUS','DIAGNOSTIC_SUMMARY','SUPPORT_INTAKE','LICENSE_REQUEST','LICENSE_STATUS','PRIME_PROPOSAL','PRIME_RESULT','SYSTEM_NOTICE']);
const FORBIDDEN_KEY=/(private.?key|password|passwd|secret|token|credential|authorization|cookie|pfx|pkcs12)/i;

function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value;}
function canonical(value){return JSON.stringify(stable(value));}
function sha256(value){return crypto.createHash('sha256').update(typeof value==='string'?value:canonical(value),'utf8').digest('hex');}
function validP256Jwk(jwk){return Boolean(jwk&&jwk.kty==='EC'&&jwk.crv==='P-256'&&typeof jwk.x==='string'&&typeof jwk.y==='string');}
function verifyP256(jwk,payload,signature){try{if(!validP256Jwk(jwk)||typeof signature!=='string'||!signature)return false;const key=crypto.createPublicKey({key:jwk,format:'jwk'});return crypto.verify('sha256',Buffer.from(canonical(payload),'utf8'),{key,dsaEncoding:'ieee-p1363'},Buffer.from(signature,'base64url'));}catch{return false;}}
function safeRole(value){const role=String(value||'').trim().toUpperCase();return ROLES.has(role)?role:'';}
function validInstallId(value){return /^[A-Za-z0-9._:-]{3,128}$/.test(String(value||''));}
function validNodeId(value){return /^[a-z0-9-]{12,96}$/i.test(String(value||''));}
function validMessageId(value){return /^[A-Za-z0-9._:-]{8,128}$/.test(String(value||''));}
function validCorrelationId(value){return /^[A-Za-z0-9._:-]{0,128}$/.test(String(value||''));}
function nodeMatchesRole(nodeId,role){return String(nodeId||'').toLowerCase().startsWith(String(role||'').toLowerCase()+'-');}
function assertNoSecrets(value,path='$'){if(value===null||value===undefined)return;if(typeof value==='string'){if(value.length>12000)throw Object.assign(new Error('HUB_PAYLOAD_STRING_TOO_LARGE'),{status:400});return;}if(Array.isArray(value)){if(value.length>500)throw Object.assign(new Error('HUB_PAYLOAD_ARRAY_TOO_LARGE'),{status:400});value.forEach((v,i)=>assertNoSecrets(v,`${path}[${i}]`));return;}if(typeof value==='object'){for(const [k,v] of Object.entries(value)){if(FORBIDDEN_KEY.test(k))throw Object.assign(new Error('HUB_SECRET_FIELD_REJECTED'),{status:400,field:`${path}.${k}`});assertNoSecrets(v,`${path}.${k}`);}}}

export function createCommunicationHub({privateKeyB64,publicJwk,compatibilityId,databaseUrl='',requirePersistent=false}){
 const privatePem=privateKeyB64?Buffer.from(String(privateKeyB64),'base64').toString('utf8'):'';
 const serverPublicJwk=publicJwk&&typeof publicJwk==='object'?publicJwk:null;
 const enroll=new Map();
 const store=createHubStore({databaseUrl,requirePersistent});
 let readyState={ok:false,persistence:store.persistence()};
 async function ready(){ readyState=await store.init(); return readyState; }
 async function close(){ await store.close(); }
 function configured(){return Boolean(privatePem&&validP256Jwk(serverPublicJwk)&&compatibilityId&&readyState.ok);}
 function signCompact(payload){if(!privatePem||!validP256Jwk(serverPublicJwk)||!compatibilityId)throw Object.assign(new Error('HUB_SIGNING_NOT_CONFIGURED'),{status:503});const p64=Buffer.from(canonical(payload),'utf8').toString('base64url');const sig=crypto.sign('sha256',Buffer.from(p64,'utf8'),{key:privatePem,dsaEncoding:'ieee-p1363'});if(sig.length!==64)throw Object.assign(new Error('HUB_SIGNING_FAILED'),{status:500});return `${p64}.${sig.toString('base64url')}`;}
 function verifyCompact(compact){try{const [p64,s64,extra]=String(compact||'').split('.');if(!p64||!s64||extra||!validP256Jwk(serverPublicJwk))return null;const key=crypto.createPublicKey({key:serverPublicJwk,format:'jwk'});if(!crypto.verify('sha256',Buffer.from(p64,'utf8'),{key,dsaEncoding:'ieee-p1363'},Buffer.from(s64,'base64url')))return null;return JSON.parse(Buffer.from(p64,'base64url').toString('utf8'));}catch{return null;}}
 function cleanupEnroll(){const now=Date.now();for(const [id,ch] of enroll)if(now>Date.parse(ch.expiresAt))enroll.delete(id);}
 function protocol(){return{schema:'NEXO_COMM_PROTOCOL_V1',protocolVersion:PROTOCOL_VERSION,compatibilityId,roles:[...ROLES],messageTypes:[...MESSAGE_TYPES],transport:'HTTPS_POLL_ACK',delivery:'AT_LEAST_ONCE_ROLE_QUEUE_WITH_NODE_TARGETING',persistence:store.persistence(),authentication:'ECDSA_P256_SELF_ENROLLMENT_PLUS_GATEWAY_SIGNED_CREDENTIAL',nodeTargeting:true,maxPayloadBytes:MAX_PAYLOAD_BYTES,maxMessageTtlSeconds:MAX_MESSAGE_TTL_MS/1000,remoteMutation:false,autoSendOnReconnect:false};}
 function challenge({role,installId}){cleanupEnroll();role=safeRole(role);installId=String(installId||'').trim();if(!role)throw Object.assign(new Error('HUB_ROLE_INVALID'),{status:400});if(!validInstallId(installId))throw Object.assign(new Error('HUB_INSTALL_ID_INVALID'),{status:400});const now=new Date(),expires=new Date(now.getTime()+ENROLL_TTL_MS);const item={schema:'NEXO_HUB_ENROLL_CHALLENGE_V1',compatibilityId,challengeId:crypto.randomUUID(),nodeId:`${role.toLowerCase()}-${crypto.randomUUID()}`,role,installId,nonce:crypto.randomBytes(24).toString('base64url'),issuedAt:now.toISOString(),expiresAt:expires.toISOString()};enroll.set(item.challengeId,item);return item;}
 function complete(body){cleanupEnroll();if(!privatePem||!validP256Jwk(serverPublicJwk)||!compatibilityId)throw Object.assign(new Error('HUB_SIGNING_NOT_CONFIGURED'),{status:503});const ch=enroll.get(String(body?.challengeId||''));if(!ch)throw Object.assign(new Error('HUB_ENROLL_CHALLENGE_NOT_FOUND'),{status:400});if(Date.now()>Date.parse(ch.expiresAt)){enroll.delete(ch.challengeId);throw Object.assign(new Error('HUB_ENROLL_CHALLENGE_EXPIRED'),{status:400});}for(const k of ['nodeId','role','installId','nonce'])if(String(body?.[k]||'')!==String(ch[k]))throw Object.assign(new Error(`HUB_ENROLL_MISMATCH_${k}`),{status:400});const publicKey=body?.publicJwk;if(!validP256Jwk(publicKey))throw Object.assign(new Error('HUB_PUBLIC_KEY_INVALID'),{status:400});const enrollment={schema:'NEXO_HUB_ENROLLMENT_V1',compatibilityId,challengeId:ch.challengeId,nodeId:ch.nodeId,role:ch.role,installId:ch.installId,nonce:ch.nonce,publicJwk:publicKey};if(!verifyP256(publicKey,enrollment,String(body?.signature||'')))throw Object.assign(new Error('HUB_ENROLL_SIGNATURE_INVALID'),{status:400});const now=new Date(),expires=new Date(now.getTime()+CREDENTIAL_TTL_MS);const credentialPayload={schema:'NEXO_HUB_NODE_CREDENTIAL_V1',compatibilityId,nodeId:ch.nodeId,role:ch.role,installIdHash:sha256(ch.installId),publicJwk:publicKey,issuedAt:now.toISOString(),expiresAt:expires.toISOString(),transport:'MESSAGE_ONLY',remoteMutation:false};const credential=signCompact(credentialPayload);enroll.delete(ch.challengeId);return{credential,node:{nodeId:ch.nodeId,role:ch.role,installId:ch.installId,expiresAt:credentialPayload.expiresAt}};}
 function verifyCredential(compact){const c=verifyCompact(compact);if(!c||c.schema!=='NEXO_HUB_NODE_CREDENTIAL_V1'||c.compatibilityId!==compatibilityId)throw Object.assign(new Error('HUB_CREDENTIAL_INVALID'),{status:401});if(Date.now()>Date.parse(c.expiresAt||''))throw Object.assign(new Error('HUB_CREDENTIAL_EXPIRED'),{status:401});if(!safeRole(c.role)||!validNodeId(c.nodeId)||!nodeMatchesRole(c.nodeId,c.role)||!validP256Jwk(c.publicJwk))throw Object.assign(new Error('HUB_CREDENTIAL_INVALID'),{status:401});if(c.remoteMutation!==false||c.transport!=='MESSAGE_ONLY')throw Object.assign(new Error('HUB_CREDENTIAL_SCOPE_INVALID'),{status:401});return c;}
 function verifySigned(credentialCompact,payload,signature){const c=verifyCredential(credentialCompact);if(!payload||typeof payload!=='object'||Array.isArray(payload))throw Object.assign(new Error('HUB_SIGNED_PAYLOAD_INVALID'),{status:400});if(String(payload.nodeId||payload.sourceNodeId||'')!==c.nodeId)throw Object.assign(new Error('HUB_NODE_MISMATCH'),{status:403});const claimedRole=String(payload.role||payload.sourceRole||'').toUpperCase();if(claimedRole!==c.role)throw Object.assign(new Error('HUB_ROLE_MISMATCH'),{status:403});if(!verifyP256(c.publicJwk,payload,String(signature||'')))throw Object.assign(new Error('HUB_REQUEST_SIGNATURE_INVALID'),{status:401});return c;}
 function validateFreshIssuedAt(value,maxSkewMs=5*60*1000){const ms=Date.parse(String(value||''));if(!Number.isFinite(ms)||Math.abs(Date.now()-ms)>maxSkewMs)throw Object.assign(new Error('HUB_REQUEST_TIME_INVALID'),{status:400});}
 function verifyNodeRequest(body,{schema='',role=''}={}){const req=body?.request,c=verifySigned(body?.credential,req,body?.signature);if(schema&&String(req?.schema||'')!==schema)throw Object.assign(new Error('HUB_NODE_REQUEST_SCHEMA_INVALID'),{status:400});validateFreshIssuedAt(req?.issuedAt);if(role&&c.role!==String(role).toUpperCase())throw Object.assign(new Error('HUB_NODE_REQUEST_ROLE_INVALID'),{status:403});if(req?.compatibilityId!==compatibilityId)throw Object.assign(new Error('HUB_COMPATIBILITY_MISMATCH'),{status:409});return{nodeId:c.nodeId,role:c.role,request:req};}
 async function trustedSend({sourceRole,sourceNodeId,targetRole,targetNodeId='',type,payload,correlationId='',taskId='',ttlSeconds=120}={}){if(!readyState.ok)throw Object.assign(new Error('HUB_STORE_NOT_READY'),{status:503});sourceRole=safeRole(sourceRole);targetRole=safeRole(targetRole);type=String(type||'').toUpperCase();sourceNodeId=String(sourceNodeId||'').trim();targetNodeId=String(targetNodeId||'').trim();if(!sourceRole||!targetRole)throw Object.assign(new Error('HUB_ROLE_INVALID'),{status:400});if(!validNodeId(sourceNodeId)||!nodeMatchesRole(sourceNodeId,sourceRole))throw Object.assign(new Error('HUB_SOURCE_NODE_INVALID'),{status:400});if(targetNodeId&&(!validNodeId(targetNodeId)||!nodeMatchesRole(targetNodeId,targetRole)))throw Object.assign(new Error('HUB_TARGET_NODE_INVALID'),{status:400});if(!MESSAGE_TYPES.has(type))throw Object.assign(new Error('HUB_MESSAGE_TYPE_INVALID'),{status:400});if(sourceRole===targetRole&&type!=='HEARTBEAT')throw Object.assign(new Error('HUB_LOOPBACK_REJECTED'),{status:400});assertNoSecrets(payload);const bytes=Buffer.byteLength(canonical(payload??null));if(bytes>MAX_PAYLOAD_BYTES)throw Object.assign(new Error('HUB_PAYLOAD_TOO_LARGE'),{status:413});ttlSeconds=Math.max(30,Math.min(MAX_MESSAGE_TTL_MS/1000,Number(ttlSeconds)||120));const now=new Date(),envelope={schema:'NEXO_COMM_ENVELOPE_V1',schemaVersion:1,compatibilityId,messageId:`MSG-${crypto.randomUUID()}`,taskId:String(taskId||'').slice(0,128),correlationId:String(correlationId||`COR-${crypto.randomUUID()}`).slice(0,128),sourceRole,sourceNodeId,targetRole,targetNodeId,type,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+ttlSeconds*1000).toISOString(),payload:payload??null,payloadHash:sha256(payload??null)};if(!validCorrelationId(envelope.correlationId))throw Object.assign(new Error('HUB_CORRELATION_ID_INVALID'),{status:400});const stored=await store.put({messageId:envelope.messageId,envelopeHash:sha256(envelope),targetRole,targetNodeId,expiresAt:envelope.expiresAt,envelope:stable(envelope)});if(stored.conflict)throw Object.assign(new Error('HUB_MESSAGE_ID_CONFLICT'),{status:409});return{accepted:true,duplicate:!!stored.duplicate,messageId:envelope.messageId,sequence:stored.sequence,envelope};}
 async function trustedPoll({role,nodeId,afterSequence=0,limit=20}={}){if(!readyState.ok)throw Object.assign(new Error('HUB_STORE_NOT_READY'),{status:503});role=safeRole(role);nodeId=String(nodeId||'');if(!role||!validNodeId(nodeId)||!nodeMatchesRole(nodeId,role))throw Object.assign(new Error('HUB_TRUSTED_POLL_INVALID'),{status:400});const messages=await store.poll({role,nodeId,afterSequence:Number(afterSequence)||0,limit:Math.max(1,Math.min(50,Number(limit)||20))});return{role,nodeId,messages,pending:messages.length,lastSequence:messages.length?messages[messages.length-1].sequence:Number(afterSequence)||0};}
 async function trustedAck({role,nodeId,messageIds=[]}={}){if(!readyState.ok)throw Object.assign(new Error('HUB_STORE_NOT_READY'),{status:503});role=safeRole(role);nodeId=String(nodeId||'');if(!role||!validNodeId(nodeId)||!nodeMatchesRole(nodeId,role))throw Object.assign(new Error('HUB_TRUSTED_ACK_INVALID'),{status:400});const ids=[...new Set((Array.isArray(messageIds)?messageIds:[]).map(String).filter(validMessageId))].slice(0,100);if(!ids.length)return{acked:0};return store.ack({role,nodeId,messageIds:ids});}
 async function send(body){if(!readyState.ok)throw Object.assign(new Error('HUB_STORE_NOT_READY'),{status:503});const env=body?.envelope;const c=verifySigned(body?.credential,env,body?.signature);if(env.schema!=='NEXO_COMM_ENVELOPE_V1'||Number(env.schemaVersion)!==1)throw Object.assign(new Error('HUB_SCHEMA_INVALID'),{status:400});if(env.compatibilityId!==compatibilityId)throw Object.assign(new Error('HUB_COMPATIBILITY_MISMATCH'),{status:409});if(!validMessageId(env.messageId))throw Object.assign(new Error('HUB_MESSAGE_ID_INVALID'),{status:400});if(!validCorrelationId(env.correlationId||''))throw Object.assign(new Error('HUB_CORRELATION_ID_INVALID'),{status:400});const targetRole=safeRole(env.targetRole);if(!targetRole)throw Object.assign(new Error('HUB_TARGET_ROLE_INVALID'),{status:400});const targetNodeId=String(env.targetNodeId||'').trim();if(targetNodeId&&(!validNodeId(targetNodeId)||!nodeMatchesRole(targetNodeId,targetRole)))throw Object.assign(new Error('HUB_TARGET_NODE_INVALID'),{status:400});if(!MESSAGE_TYPES.has(String(env.type||'').toUpperCase()))throw Object.assign(new Error('HUB_MESSAGE_TYPE_INVALID'),{status:400});if(c.role===targetRole&&env.type!=='HEARTBEAT')throw Object.assign(new Error('HUB_LOOPBACK_REJECTED'),{status:400});const createdMs=Date.parse(String(env.createdAt||'')),expiresMs=Date.parse(String(env.expiresAt||''));if(!Number.isFinite(createdMs)||!Number.isFinite(expiresMs)||createdMs>Date.now()+60000||expiresMs<=Date.now()||expiresMs-createdMs>MAX_MESSAGE_TTL_MS)throw Object.assign(new Error('HUB_MESSAGE_TTL_INVALID'),{status:400});assertNoSecrets(env.payload);const payloadBytes=Buffer.byteLength(canonical(env.payload??null));if(payloadBytes>MAX_PAYLOAD_BYTES)throw Object.assign(new Error('HUB_PAYLOAD_TOO_LARGE'),{status:413});const payloadHash=sha256(env.payload??null);if(String(env.payloadHash||'').toLowerCase()!==payloadHash)throw Object.assign(new Error('HUB_PAYLOAD_HASH_MISMATCH'),{status:400});const envelopeHash=sha256(env);const stored=await store.put({messageId:env.messageId,envelopeHash,targetRole,targetNodeId,expiresAt:env.expiresAt,envelope:stable(env)});if(stored.conflict)throw Object.assign(new Error('HUB_MESSAGE_ID_CONFLICT'),{status:409});return{accepted:true,duplicate:!!stored.duplicate,messageId:env.messageId,sequence:stored.sequence,targetRole,targetNodeId:targetNodeId||null};}
 async function poll(body){if(!readyState.ok)throw Object.assign(new Error('HUB_STORE_NOT_READY'),{status:503});const p=body?.poll,c=verifySigned(body?.credential,p,body?.signature);if(p.schema!=='NEXO_HUB_POLL_V1')throw Object.assign(new Error('HUB_POLL_SCHEMA_INVALID'),{status:400});validateFreshIssuedAt(p.issuedAt);const limit=Math.max(1,Math.min(50,Number(p.limit)||20)),after=Math.max(0,Number(p.afterSequence)||0);const messages=await store.poll({role:c.role,nodeId:c.nodeId,afterSequence:after,limit});return{role:c.role,nodeId:c.nodeId,messages,pending:messages.length,lastSequence:messages.length?messages[messages.length-1].sequence:after,delivery:'AT_LEAST_ONCE',nodeTargeting:true};}
 async function ack(body){if(!readyState.ok)throw Object.assign(new Error('HUB_STORE_NOT_READY'),{status:503});const a=body?.ack,c=verifySigned(body?.credential,a,body?.signature);if(a.schema!=='NEXO_HUB_ACK_V1')throw Object.assign(new Error('HUB_ACK_SCHEMA_INVALID'),{status:400});validateFreshIssuedAt(a.issuedAt);const ids=Array.isArray(a.messageIds)?[...new Set(a.messageIds.map(String).filter(validMessageId))].slice(0,100):[];if(!ids.length)throw Object.assign(new Error('HUB_ACK_EMPTY'),{status:400});const result=await store.ack({role:c.role,nodeId:c.nodeId,messageIds:ids});return{acked:result.acked,role:c.role,nodeId:c.nodeId,messageIds:ids};}
 async function status(){const s=readyState.ok?await store.status():{persistence:store.persistence(),queues:{CLIENTE:0,MASTER:0,NEXA:0},total:0};return{configured:configured(),protocolVersion:PROTOCOL_VERSION,compatibilityId,nodeTargeting:true,remoteMutation:false,autoSendOnReconnect:false,persistence:s.persistence,queues:s.queues,total:s.total,ready:!!readyState.ok};}
 return{configured,ready,close,protocol,challenge,complete,send,poll,ack,status,verifyNodeRequest,trustedSend,trustedPoll,trustedAck};
}
