import {Pool} from 'pg';

export class PostgresMobileStore{
  constructor({databaseUrl,now=()=>Date.now()}={}){if(!String(databaseUrl||'').trim())throw new Error('MOBILE_DATABASE_URL_REQUIRED');this.now=now;this.pool=new Pool({connectionString:databaseUrl,ssl:String(databaseUrl).includes('localhost')?false:{rejectUnauthorized:false},max:4});}
  async init(){await this.pool.query(`CREATE TABLE IF NOT EXISTS nexo_mobile_pairings(pairing_id text PRIMARY KEY,token_hash text NOT NULL,nexa_node_id text NOT NULL,scopes jsonb NOT NULL,label text NOT NULL,created_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,consumed_at timestamptz);CREATE INDEX IF NOT EXISTS idx_nexo_mobile_pairings_exp ON nexo_mobile_pairings(expires_at);CREATE TABLE IF NOT EXISTS nexo_mobile_sessions(session_hash text PRIMARY KEY,session_id text UNIQUE NOT NULL,device_id text NOT NULL,label text NOT NULL,platform text NOT NULL,nexa_node_id text NOT NULL,scopes jsonb NOT NULL,created_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,last_seen_at timestamptz NOT NULL,revoked_at timestamptz);CREATE INDEX IF NOT EXISTS idx_nexo_mobile_sessions_exp ON nexo_mobile_sessions(expires_at);CREATE TABLE IF NOT EXISTS nexo_mobile_tickets(id text PRIMARY KEY,protocol text UNIQUE NOT NULL,session_id text NOT NULL,device_id text NOT NULL,nexa_node_id text NOT NULL,subject text NOT NULL,description text NOT NULL,priority text NOT NULL,status text NOT NULL,created_at timestamptz NOT NULL);CREATE INDEX IF NOT EXISTS idx_nexo_mobile_tickets_session ON nexo_mobile_tickets(session_id,created_at DESC);CREATE TABLE IF NOT EXISTS nexo_mobile_presence(nexa_node_id text PRIMARY KEY,last_seen_at timestamptz NOT NULL);`);return{ok:true,persistence:'POSTGRES'};}
  async close(){await this.pool.end();}
  async createPairing(r){await this.pool.query('INSERT INTO nexo_mobile_pairings(pairing_id,token_hash,nexa_node_id,scopes,label,created_at,expires_at,consumed_at) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,NULL)',[r.pairingId,r.tokenHash,r.nexaNodeId,JSON.stringify(r.scopes),r.label,r.createdAt,r.expiresAt]);return r;}
  async consumePairing({pairingId,tokenHash}){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM nexo_mobile_pairings WHERE pairing_id=$1 FOR UPDATE',[pairingId]);if(!q.rowCount)throw new Error('MOBILE_PAIRING_NOT_FOUND');const x=q.rows[0];if(x.consumed_at)throw new Error('MOBILE_PAIRING_REPLAY');if(Date.now()>Date.parse(x.expires_at))throw new Error('MOBILE_PAIRING_EXPIRED');if(x.token_hash!==tokenHash)throw new Error('MOBILE_PAIRING_TOKEN_INVALID');const at=new Date(this.now()).toISOString();await c.query('UPDATE nexo_mobile_pairings SET consumed_at=$2 WHERE pairing_id=$1',[pairingId,at]);await c.query('COMMIT');return{pairingId:x.pairing_id,tokenHash:x.token_hash,nexaNodeId:x.nexa_node_id,scopes:x.scopes,label:x.label,createdAt:new Date(x.created_at).toISOString(),expiresAt:new Date(x.expires_at).toISOString(),consumedAt:at};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async createSession(r){await this.pool.query('INSERT INTO nexo_mobile_sessions(session_hash,session_id,device_id,label,platform,nexa_node_id,scopes,created_at,expires_at,last_seen_at,revoked_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,NULL)',[r.sessionHash,r.sessionId,r.deviceId,r.label,r.platform,r.nexaNodeId,JSON.stringify(r.scopes),r.createdAt,r.expiresAt,r.lastSeenAt]);return r;}
  async getSession(hash){const q=await this.pool.query('SELECT * FROM nexo_mobile_sessions WHERE session_hash=$1 AND revoked_at IS NULL',[hash]);if(!q.rowCount)return null;const x=q.rows[0],expired=this.now()>Date.parse(x.expires_at);if(!expired)await this.pool.query('UPDATE nexo_mobile_sessions SET last_seen_at=NOW() WHERE session_hash=$1',[hash]);return{sessionHash:x.session_hash,sessionId:x.session_id,deviceId:x.device_id,label:x.label,platform:x.platform,nexaNodeId:x.nexa_node_id,scopes:x.scopes,createdAt:new Date(x.created_at).toISOString(),expiresAt:new Date(x.expires_at).toISOString(),lastSeenAt:new Date(x.last_seen_at).toISOString(),revokedAt:x.revoked_at?new Date(x.revoked_at).toISOString():null,expired};}
  async addTicket(r){await this.pool.query('INSERT INTO nexo_mobile_tickets(id,protocol,session_id,device_id,nexa_node_id,subject,description,priority,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[r.id,r.protocol,r.sessionId,r.deviceId,r.nexaNodeId,r.subject,r.description,r.priority,r.status,r.createdAt]);return r;}
  async listTickets(sessionId){const q=await this.pool.query('SELECT * FROM nexo_mobile_tickets WHERE session_id=$1 ORDER BY created_at DESC LIMIT 100',[sessionId]);return q.rows.map(x=>({id:x.id,protocol:x.protocol,sessionId:x.session_id,deviceId:x.device_id,nexaNodeId:x.nexa_node_id,subject:x.subject,description:x.description,priority:x.priority,status:x.status,createdAt:new Date(x.created_at).toISOString()}));}
  async heartbeat({nexaNodeId,at}){await this.pool.query('INSERT INTO nexo_mobile_presence(nexa_node_id,last_seen_at) VALUES($1,$2) ON CONFLICT(nexa_node_id) DO UPDATE SET last_seen_at=EXCLUDED.last_seen_at',[nexaNodeId,at]);return{nexaNodeId,lastSeenAt:at};}
  async presenceOf(nexaNodeId){const q=await this.pool.query('SELECT last_seen_at FROM nexo_mobile_presence WHERE nexa_node_id=$1',[nexaNodeId]);return q.rowCount?new Date(q.rows[0].last_seen_at).toISOString():null;}
}