import crypto from 'node:crypto';
import {sha256} from './mobile_store.mjs';

export const COMPATIBILITY_ID='NEXO-SUITE-PRIME-R8-P5-MOBILE-20260911';
export const PAIRING_SCHEMA='NEXO_MOBILE_PAIRING_V1';
export const SESSION_SCHEMA='NEXO_MOBILE_SESSION_V1';
export const PROTOCOL_SCHEMA='NEXO_MOBILE_COMPANION_PROTOCOL_V1';
export const SUPPORT_REQUEST_SCHEMA='NEXO_MOBILE_SUPPORT_REQUEST_V1';
export const SUPPORT_RESPONSE_SCHEMA='NEXO_MOBILE_SUPPORT_RESPONSE_V1';
const ALLOWED_SCOPES=['support:ask','knowledge:read','tickets:read','tickets:create','status:read'];
const SECRET_KEY=/(password|passwd|private.?key|api.?key|secret|credential|authorization|cookie|pfx|p12|pkcs12|pem|master.?key|claim.?secret)/i;
const SECRET_VALUE=/(-----BEGIN (?:EC |RSA |)PRIVATE KEY-----|\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b|\bBearer\s+[A-Za-z0-9._~+\/-]{24,})/i;
const CRITICAL=/(\b(?:delete|drop|truncate|restore|shell|exec|format|wipe)\b|\b(?:apague|delete|remova|exclua)\b.{0,35}\b(?:banco|database|arquivo|backup)\b)/i;
function randomToken(randomBytes){return randomBytes(32).toString('base64url');}
function scopes(input){if(!Array.isArray(input)||!input.length)throw new Error('MOBILE_SCOPES_REQUIRED');const out=[];for(const x of input){const s=String(x||'').trim();if(!ALLOWED_SCOPES.includes(s))throw new Error('MOBILE_SCOPE_REJECTED');if(!out.includes(s))out.push(s);}return out;}
function safe(value,path='$'){if(value==null)return;if(typeof value==='string'){if(SECRET_VALUE.test(value))throw new Error('MOBILE_SECRET_VALUE_REJECTED');if(Buffer.byteLength(value)>65536)throw new Error('MOBILE_PAYLOAD_TOO_LARGE');return;}if(Array.isArray(value)){if(value.length>500)throw new Error('MOBILE_PAYLOAD_TOO_LARGE');return value.forEach((v,i)=>safe(v,`${path}[${i}]`));}if(typeof value==='object'){for(const[k,v]of Object.entries(value)){if(SECRET_KEY.test(k))throw new Error(`MOBILE_SECRET_FIELD_REJECTED:${path}.${k}`);safe(v,`${path}.${k}`);}return;}if(!['number','boolean'].includes(typeof value))throw new Error('MOBILE_PAYLOAD_TYPE_REJECTED');}
function validNode(v,prefix='nexa-'){return String(v||'').startsWith(prefix)&&/^[a-z0-9-]{12,96}$/i.test(String(v||''));}
function cleanDevice(v){const x=String(v||'').trim();if(!/^[A-Za-z0-9._:-]{3,128}$/.test(x))throw new Error('MOBILE_DEVICE_ID_INVALID');return x;}

export class MobileGatewayService{
  constructor({store,hub,now=()=>Date.now(),randomBytes=crypto.randomBytes,randomUUID=crypto.randomUUID,sleep=ms=>new Promise(r=>setTimeout(r,ms)),pairingTtlMs=8*60*1000,sessionTtlMs=8*60*60*1000,answerTimeoutMs=12000,pollIntervalMs=120}={}){
    if(!store||!hub)throw new Error('MOBILE_GATEWAY_DEPS_REQUIRED');this.store=store;this.hub=hub;this.now=now;this.randomBytes=randomBytes;this.randomUUID=randomUUID;this.sleep=sleep;this.pairingTtlMs=Math.max(30_000,Math.min(10*60*1000,pairingTtlMs));this.sessionTtlMs=Math.max(60_000,Math.min(24*60*60*1000,sessionTtlMs));this.answerTimeoutMs=Math.max(1000,Math.min(25000,answerTimeoutMs));this.pollIntervalMs=Math.max(20,Math.min(1000,pollIntervalMs));
  }
  protocol(){return {schema:PROTOCOL_SCHEMA,protocolVersion:'1.1.0-r10.26',compatibilityId:COMPATIBILITY_ID,transport:'HTTPS_HUB_BRIDGE',scopes:[...ALLOWED_SCOPES],remoteMutation:false,autoSendOnReconnect:false,pairing:'ONE_TIME_HASHED_TOKEN',session:'HASHED_SERVER_SESSION',supportFlow:'IPHONE_GATEWAY_HUB_NEXA_PRIME'};}
  async createPairingFromNexa({nexaNodeId,requestedScopes,label='iPhone'}){if(!validNode(nexaNodeId))throw new Error('MOBILE_NEXA_NODE_INVALID');const sc=scopes(requestedScopes),token=randomToken(this.randomBytes),now=this.now(),pairingId=`NXMP-${this.randomUUID().replace(/-/g,'')}`;const record={pairingId,tokenHash:sha256(token),nexaNodeId,scopes:sc,label:String(label||'iPhone').slice(0,80),createdAt:new Date(now).toISOString(),expiresAt:new Date(now+this.pairingTtlMs).toISOString(),consumedAt:null};await this.store.createPairing(record);return {schema:PAIRING_SCHEMA,schemaVersion:1,compatibilityId:COMPATIBILITY_ID,pairingId,pairingToken:token,createdAt:record.createdAt,expiresAt:record.expiresAt,scopes:sc};}
  async claimPairing({pairing,device}){if(pairing?.schema!==PAIRING_SCHEMA||pairing?.compatibilityId!==COMPATIBILITY_ID)throw new Error('MOBILE_PAIRING_SCHEMA_INVALID');const p=await this.store.consumePairing({pairingId:String(pairing.pairingId||''),tokenHash:sha256(String(pairing.pairingToken||''))});const deviceId=cleanDevice(device?.deviceId),token=randomToken(this.randomBytes),now=this.now(),sessionId=`NXMS-${this.randomUUID().replace(/-/g,'')}`;const rec={sessionId,sessionHash:sha256(token),deviceId,label:String(device?.label||p.label||'iPhone').slice(0,80),platform:'IOS_PWA',nexaNodeId:p.nexaNodeId,scopes:[...p.scopes],createdAt:new Date(now).toISOString(),expiresAt:new Date(now+this.sessionTtlMs).toISOString(),revokedAt:null,lastSeenAt:new Date(now).toISOString()};await this.store.createSession(rec);return {schema:SESSION_SCHEMA,sessionToken:token,expiresAt:rec.expiresAt,deviceId,scopes:rec.scopes};}
  async auth(sessionToken,scope){const token=String(sessionToken||'');if(!token)throw new Error('MOBILE_SESSION_REQUIRED');const s=await this.store.getSession(sha256(token));if(!s)throw new Error('MOBILE_SESSION_INVALID');if(s.expired)throw new Error('MOBILE_SESSION_EXPIRED');if(scope&&!s.scopes.includes(scope))throw new Error(`MOBILE_SCOPE_REQUIRED:${scope}`);return s;}
  pseudoNode(session){return `cliente-mobile-${sha256(session.sessionId).slice(0,24)}`;}
  async ask(sessionToken,{question,context={}}={}){const session=await this.auth(sessionToken,'support:ask'),q=String(question||'').trim().slice(0,4000);if(!q)throw new Error('MOBILE_QUESTION_REQUIRED');if(CRITICAL.test(q))throw new Error('MOBILE_CRITICAL_REQUEST_REJECTED');safe(q);safe(context);const mobileRequestId=`NXMR-${this.randomUUID().replace(/-/g,'').slice(0,24)}`,correlationId=`MOB-${this.randomUUID()}`,nodeId=this.pseudoNode(session),payload={schema:SUPPORT_REQUEST_SCHEMA,mobileRequestId,deviceId:session.deviceId,question:q,context:{...context,channel:'IOS_PWA_R10_26'}};await this.hub.trustedSend({sourceRole:'CLIENTE',sourceNodeId:nodeId,targetRole:'NEXA',targetNodeId:session.nexaNodeId,type:'SUPPORT_REQUEST',correlationId,payload,ttlSeconds:120});const deadline=this.now()+this.answerTimeoutMs;do{const polled=await this.hub.trustedPoll({role:'CLIENTE',nodeId,afterSequence:0,limit:20});for(const item of polled.messages||[]){const e=item.envelope||{};if(e.type==='SUPPORT_MESSAGE'&&e.correlationId===correlationId&&e.payload?.schema===SUPPORT_RESPONSE_SCHEMA&&e.payload?.mobileRequestId===mobileRequestId){safe(e.payload);await this.hub.trustedAck({role:'CLIENTE',nodeId,messageIds:[e.messageId]});return {ok:true,mobileRequestId,answer:String(e.payload.answer||''),status:String(e.payload.status||''),confidence:e.payload.confidence??null,evidence:Array.isArray(e.payload.evidence)?e.payload.evidence:[]};}}if(this.now()>=deadline)break;await this.sleep(this.pollIntervalMs);}while(true);throw new Error('MOBILE_NEXA_TIMEOUT');}
  async createTicket(sessionToken,ticket={}){const s=await this.auth(sessionToken,'tickets:create'),subject=String(ticket.subject||'').trim().slice(0,120),description=String(ticket.description||'').trim().slice(0,4000),priority=String(ticket.priority||'P4').toUpperCase();if(!subject||!description)throw new Error('MOBILE_TICKET_FIELDS_REQUIRED');if(!/^P[1-4]$/.test(priority))throw new Error('MOBILE_TICKET_PRIORITY_INVALID');safe({subject,description});const id=`NXMT-${this.randomUUID().replace(/-/g,'').slice(0,20)}`,protocol=`MOB-${new Date(this.now()).toISOString().slice(0,10).replace(/-/g,'')}-${id.slice(-6)}`,rec={id,protocol,sessionId:s.sessionId,deviceId:s.deviceId,nexaNodeId:s.nexaNodeId,subject,description,priority,status:'ABERTO',createdAt:new Date(this.now()).toISOString()};await this.store.addTicket(rec);return rec;}
  async listTickets(sessionToken){const s=await this.auth(sessionToken,'tickets:read');return this.store.listTickets(s.sessionId);}
  async heartbeatFromNexa(nexaNodeId){if(!validNode(nexaNodeId))throw new Error('MOBILE_NEXA_NODE_INVALID');return this.store.heartbeat({nexaNodeId,at:new Date(this.now()).toISOString()});}
  async status(sessionToken){const s=await this.auth(sessionToken,'status:read'),hub=await this.hub.status(),last=await this.store.presenceOf(s.nexaNodeId),age=last?this.now()-Date.parse(last):Infinity;return {paired:true,deviceId:s.deviceId,nexaNodeId:s.nexaNodeId,nexa:age<=60_000?'ONLINE':(last?'OFFLINE':'UNKNOWN'),lastSeenAt:last,hub:{ready:!!hub.ready,persistence:hub.persistence||null,total:Number(hub.total)||0},client:'MOBILE',master:'NÃO EXPOSTO'};}
}