<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
  <ItemGroup><PackageReference Include="xunit.v3.mtp-v2" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../src/Playloud.SafeRelease/Playloud.SafeRelease.csproj" /></ItemGroup>
</Project>
